export const portfolioData = {
  name: "D Eeshan Pavan Karteek",
  title: "Software & Machine Learning Engineer",
  summary: "Computer Science (AI & ML) undergraduate with experience in Machine Learning, Backend Development, and Distributed Systems. Built scalable applications using Python, Java, Node.js, React, TensorFlow, and Kafka. Developed real-time optimization systems, deep learning models, and multi-tenant web platforms with measurable improvements in performance, accuracy, and efficiency.",
  contact: {
    phone: "+91-81066 17544",
    email: "eeshankarteek26@gmail.com",
    github: "https://github.com/Iameeshan26",
    linkedin: "https://www.linkedin.com/in/dontarajueeshan/",
  },
  education: {
    degree: "B.Tech in Computer Science and Engineering (AI & ML)",
    institution: "Sri Venkateswara College of Engineering",
    cgpa: "8.93",
    period: "2022 - 2026",
  },
  skills: [
    { category: "Languages", items: ["Python", "Java", "C", "TypeScript", "JavaScript"] },
    { category: "Frontend", items: ["HTML", "CSS", "Vite", "React"] },
    { category: "Backend", items: ["Node.js", "Express.js", "REST APIs", "Flask"] },
    { category: "Machine Learning & AI", items: ["TensorFlow", "Scikit-Learn", "XGBoost", "CNNs", "Deep Learning", "Generative AI", "Gemini API"] },
    { category: "Databases", items: ["MySQL", "PostgreSQL", "Firebase", "PostGIS", "JSON Database"] },
    { category: "Tools & Technologies", items: ["Kafka", "Git", "GitHub", "JWT", "BcryptJS", "OR-Tools", "Pandas"] },
    { category: "AI & Generative AI", items: ["Prompt Engineering", "LLM Applications", "AI Agents"] },
  ],
  projects: [
    {
      title: "Last-Mile Logistics Optimizer",
      technologies: ["Python", "OR-Tools", "Kafka", "XGBoost", "PostGIS", "TomTom API"],
      description: "Built a real-time route optimization platform integrating live traffic and weather data.",
      points: [
        "Reduced fuel costs by 20% and delivery time by 15% using traffic-aware route planning.",
        "Improved ETA prediction accuracy by 25% through ML-based dwell-time estimation.",
        "Enabled sub-second route re-optimization using Kafka-driven event processing.",
        "Increased driver capacity by 10% through dynamic route adjustments.",
      ],
    },
    {
      title: "Multi-Tenant Ticketing System",
      technologies: ["React", "TypeScript", "Node.js", "Express.js", "JSON DB"],
      description: "Developed a secure multi-tenant ticketing platform with Organization-Based Access Control (OBAC).",
      points: [
        "Implemented a native SMTP listener to convert incoming emails into structured support tickets.",
        "Designed a race-condition-resistant backend using atomic JSON storage and sequential write queues.",
        "Built contextual search capabilities for efficient cross-tenant data retrieval.",
        "Enhanced security through JWT authentication and BcryptJS password hashing.",
      ],
    },
    {
      title: "Bone Fracture Classification Model",
      technologies: ["TensorFlow", "Flask", "Scikit-Learn", "XGBoost", "DenseNet121"],
      description: "Engineered and benchmarked CNN architectures for high-accuracy fracture classification.",
      points: [
        "Improved model accuracy from 84.2% to 92.4% using a hybrid DenseNet121 + XGBoost architecture.",
        "Trained on 10,000+ labeled X-ray images spanning 10 fracture classes.",
        "Deployed via Flask API for real-time inference and performance evaluation.",
      ],
    },
  ],
  experience: {
    role: "Gen AI Intern",
    company: "Smart Bridge",
    period: "Dec 2025 – Mar 2026",
    points: [
      "Developed a Generative AI application using Gemini API supporting both text and image-based inputs.",
      "Engineered an end-to-end workflow for input processing, prompt generation, and response orchestration.",
      "Automated recipe generation and nutritional analysis, reducing manual search effort by ~70%.",
      "Implemented image understanding pipelines to extract food information and generate contextual recommendations.",
      "Validated system performance across 20+ user scenarios and test cases.",
    ],
  },
  certificates: [
    { title: "IBM AI Fundamentals", image: "certificates/IBM AI Fundamentals.jpg" },
    { title: "Prompt Design with Vertex AI", image: "certificates/Prompot desing with vertex ai.jpg" },
    { title: "Oracle Cloud Infrastructure", image: "certificates/Oracle cloud infrastricture.jpg" },
    { title: "Develop GenAI, Streamlit Applications", image: "certificates/develope genai, streamlit applications.jpg" },
    { title: "Explore GenAI with Vertex AI", image: "certificates/explore genai with vertex ai.jpg" },
    { title: "Wipro Python", image: "certificates/wipro python.jpg" },
    { title: "Build Real World Applications", image: "certificates/build real world applicatoions.jpg" },
    { title: "Salesforce AI Associate", image: "certificates/salesforce ai associate.jpg" },
    { title: "Multimodal RAGs", image: "certificates/multimodl rags.jpg" },
    { title: "NPTEL Certificate", image: "certificates/NPTEL CERT.jpg" },
  ],
  blogs: [
    {
      title: "The Future of Scalable Systems",
      excerpt: "Exploring the next generation of multi-tenant architectures and secure data isolation.",
      date: "Coming Soon",
      category: "SDE",
      link: "",
    },
    {
      title: "Optimizing ML Pipelines",
      excerpt: "Lessons learned from building real-time logistics optimizers with sub-second response times.",
      date: "Coming Soon",
      category: "MLE",
      link: "",
    },
  ],
};
